### ISSUE TITLE
Text is truncated when using UITableViewCellAccessoryDisclosureIndicator

### ISSUE THREAD

**Issue by koenvanderdrift** [smileyborg/TableViewCellWithAutoLayout#15]
First of all, many thanks for this sample project (and PureLayout).

In my app, the cells have a disclosure indicator, and in some cases this causes the text to be truncated. I tried this in your sample code by setting `self.accessoryType = UITableViewCellAccessoryDisclosureIndicator;` inside the init method of the cell, and I see the same at the end of the body text. I'm guessing the indicator interferes with the autolayout constraints, but I don't know how and where to correct for this. I tried increasing `kLabelHorizontalInsets`, but that didn't change anything. Removing the lines that set the `lineBreakMode` also didn't help.

Any suggestions?

**Comment by koenvanderdrift** [comment]
I've noticed that adding

`[UIView autoSetPriority:UILayoutPriorityRequired - 1 forConstraints:^{
    [cell.contentView autoSetDimension:ALDimensionWidth toSize:width];
}];`

decreases the performance of the table view, especially with long tables, scrolling becomes choppy. I have confirmed this with Instruments, there is at least a three-fold difference (in my app). My hunch is the slowdown is happening because this is called for every row and I am going to try to move this code to the `updateConstraints` method of the cell, so it will be called only once. I'll post back later with an update.

**Comment by smileyborg** [comment]
That's interesting. You definitely don't want to duplicate that constraint more than once per cell, let me know how that goes. Can you also try testing the performance if you make the constraint Required priority (e.g. omit the `autoSetPriority...` call)? I know that optional constraints are more expensive to solve than Required ones, and theoretically it should work fine if the constraint is Required here.

**Comment by koenvanderdrift** [comment]
Yeah, it's much faster if I comment out the `autoSetPriority:` call.  Maybe it's an iOS7 vs iOS8 issue, still looking into that. If I understand correctly, I don't need `heightForRowAtIndexPath:` and `estimatedHeightForRowAtIndexPath:` in iOS8, but my app should work on iOS7 too so I need to keep it.

**Comment by koenvanderdrift** [comment]
Allright, it's an iOS 7/8 issue.

If I run the code in iOS7 (simulator), there are no hiccups. If I run the code in iOS8 there are hiccups. But if I completely comment out `heightForRowAtIndexPath:` and `estimatedHeightForRowAtIndexPath:`, and set the values for the `rowHeight` and `estimatedRowHeight` in `viewDidLoad`, the hiccups in iOS8 are gone.

So I need to make my code work in both iOS7 and iOS8, and asked about that on SO: http://stackoverflow.com/questions/27944801/skip-ignore-method-in-ios/27945778

**Comment by smileyborg** [comment]
Yeah, the iOS 8 self-sizing cells should be overall better than custom implementing that work yourself on iOS 7. So if possible you should use the self-sizing cell mechanism. This question asked the same question on SO already: http://stackoverflow.com/questions/26022113/how-to-only-override-a-method-depending-on-the-runtime-system-ios-version

I recommend using two different data source classes though, as opposed to conditionally making your view controller respond to that selector. But either should work.

**Comment by koenvanderdrift** [comment]
Hope it's ok to ask this question here.

I've been trying to align the two `UILabel` views next to each other, and added that to my fork.  What I see is:

1. they are lined up correctly next to each other, so that part is working
2. in iOS 7, I see all the text for the bodyLabel, but in some cases there is a lot of whitespace above and under it.
3. in iOS 8, the text of the every bodyLabel is truncated.

Note, that I shortened the string length for the bodyLabel for clarity.

See my fork here https://github.com/koenvanderdrift/TableViewCellWithAutoLayout

Any suggestions how I can fix this?

**Comment by koenvanderdrift** [comment]
I solved this by adding:

        [UIView autoSetPriority:UILayoutPriorityFittingSizeLevel forConstraints:^{
            [self.bodyLabel autoSetContentHuggingPriorityForAxis: ALAxisHorizontal];
        }];
