### ISSUE TITLE
library not found

### ISSUE THREAD

**Issue by fangliangv587** [smileyborg/TableViewCellWithAutoLayout#22]
run happened below error
ld: library not found for -lPureLayout
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by smileyborg** [comment]
Hi @fangliangv587,

Please make sure you are opening the **.xcworkspace** in Xcode, not the **.xcproj**, as noted in the README:

> To build & run the app, you should open the `TableViewCellWithAutoLayout.xcworkspace` in Xcode.

The error you're encountering happens if you try to build & run from the Xcode project, which does not include the CocoaPods project.

**Comment by smileyborg** [comment]
I realized that there was a mistake with the `.gitignore` for this repo that had prevented the `.xcworkspace` from being checked in. This was fixed in e616b5ab94e35784e3bd8cbde124ccba3c741a3b, please try opening the workspace!
