### ISSUE TITLE
iOS8 estimateHeight

### ISSUE THREAD

**Issue by MickeyHub** [smileyborg/TableViewCellWithAutoLayout#23]
I found that give a inaccurate height to estimateHeightForRow method will make tableview jump up and down, or wrong layout and scroll automatically when insert or delete row, so I use heightForRow instead of estimateHeight in iOS8 although use autolayout in cell

**Comment by smileyborg** [comment]
Hi @MickeyHub,

These are known issues (Apple bugs) with row height estimation on iOS 7 & 8. Most of these issues have been fixed as of iOS 9 though, so please test your code using the latest beta to see if it is fixed.

**Comment by MickeyHub** [comment]
Thanks @smileyborg , the workaround I used is to use heightForRowAtIndexPath to return accurate height while cell using autolayout, is it a good way? do you have other good idea? Look forward to your favourable reply ^_^.
