### ISSUE TITLE
hello editor!

### ISSUE THREAD

**Issue by j364960953** [smileyborg/TableViewCellWithAutoLayout#24]
I am download it, and use cocoapods install .It always take error "TableViewCellWithAutoLayout-Prefix.pch" on not found "#import "PureLayout.h". I don't know how to solution it, can you tell me.

**Comment by smileyborg** [comment]
Hi @j364960953,

Are you opening the workspace? Please see #22.

**Comment by smileyborg** [comment]
I realized that there was a mistake with the `.gitignore` for this repo that had prevented the `.xcworkspace` from being checked in. This was fixed in e616b5ab94e35784e3bd8cbde124ccba3c741a3b, please try opening the workspace!
