### ISSUE TITLE
Issue with UITextView

### ISSUE THREAD

**Issue by bhirt-bpl** [smileyborg/TableViewCellWithAutoLayout#6]
I changed the UILabel to a UITextView in your example and [cell.contentView systemLayoutSizeFittingSize:UILayoutFittingCompressedSize] ends up returning ridiculously large widths like {5147.5, 80.5}.   The stock example will also do this with UILabel if you comment out the preferredMaxLayoutWidth line.  I was a bit confused by this at first, because the following code/comment in the view controller seems to imply that setting cell.bounds will prevent it from happening:

```
// The cell's width must be set to the same size it will end up at once it is in the table view.
// This is important so that we'll get the correct height for different table view widths, since our cell's
// height depends on its width due to the multi-line UILabel word wrapping. Don't need to do this above in
// -[tableView:cellForRowAtIndexPath:] because it happens automatically when the cell is used in the table view.
cell.bounds = CGRectMake(0.0f, 0.0f, CGRectGetWidth(tableView.bounds), CGRectGetHeight(cell.bounds));
```

It seems [cell.contentView systemLayoutSizeFittingSize:UILayoutFittingCompressedSize] completely ignores it's bounds and that code is doing nothing.   I'm seeing this in both xcode5 and xcode6b2 with ios 7 deployment.

I ended up creating a width constraint on the the offscreen cell.contentView and getting rid of the cell.bounds code all together. You also no longer need preferredMaxLayoutWidth set in the cell's layoutSubviews which seems like a good thing.  This solutions seems to play much nicer with systemLayoutSizeFittingSize: and feels like it might be a better way to do it since everything now happens within the constraint system.

There will obviously still be issues since contentView isn't always the same width as the tableView's width -- but I don't think that was ever accounted for in the original example.

Here is the code snippet of the relevant change:

```
// Use the dictionary of offscreen cells to get a cell for the reuse identifier, creating a cell and storing
// it in the dictionary if one hasn't already been added for the reuse identifier.
// WARNING: Don't call the table view's dequeueReusableCellWithIdentifier: method here because this will result
// in a memory leak as the cell is created but never returned from the tableView:cellForRowAtIndexPath: method!
RJTableViewCell *cell = [self.offscreenCells objectForKey:reuseIdentifier];
if (!cell) {
    cell = [[RJTableViewCell alloc] init];
    NSLayoutConstraint *constraint = [cell.contentView autoSetDimension:ALDimensionWidth toSize:self.tableView.bounds.size.width];
    [self.offscreenWidthConstraints setObject:constraint forKey:reuseIdentifier];
    [self.offscreenCells setObject:cell forKey:reuseIdentifier];
}
else {
    CGSize size = tableView.bounds.size;
    NSLayoutConstraint *constraint = [self.offscreenWidthConstraints objectForKey:reuseIdentifier];
    if (constraint.constant != size.width) {
        NSLog(@"tablview width changed from %f to %f",constraint.constant,size.width);
        constraint.constant = size.width;
    }
}
```

I'm new to autolayout and this is the first time I've looked into using PureLayout, so I wanted to get your feedback on this solution before I submit a pull request.

**Comment by twigbranch** [comment]
Was this issue resolved somewhere else?  Like the poster, I'm trying to understand the best way to deal with the large unconstrained widths.

**Comment by smileyborg** [comment]
No, I believe this was closed after a couple months because @bhirt-bpl never followed up.

@twigbranch feel free to open a new issue if you have a specific question. As mentioned in this thread, if you want help debugging you should share a sample project.
